[workspace]
members = [
  # the main library and tests
  "rustls",
  # tests and example code that depend on mio
  "rustls-mio",
]
exclude = ["admin/rustfmt"]

[patches.crates-io]
webpki-roots = { path = "../webpki-roots" }
